[package]

name = "sandstorm-raw-api-example"
version = "0.0.1"
authors = [ "David Renshaw <dwrenshaw@gmail.com>" ]

[[bin]]

name = "server"
path = "src/main.rs"

[dependencies]
capnp = "0.7"
capnp-rpc = "0.7"
capnp-futures = "0.0.2"
futures = "0.1"
mio-uds = "0.6"
sandstorm = "0.0.5"
tokio-core = "0.1"

[replace]
"capnp:0.7.5" = { git = "https://github.com/dwrensha/capnproto-rust", branch = "futures" }
"capnpc:0.7.5" = { git = "https://github.com/dwrensha/capnpc-rust", branch = "futures" }
"capnp-rpc:0.7.4" = { git = "https://github.com/dwrensha/capnp-rpc-rust", branch = "futures" }
"capnp-futures:0.0.2" = { git = "https://github.com/dwrensha/capnp-futures-rs" }

