[package]

name = "sandstorm-raw-api-example"
version = "0.0.1"
authors = [ "David Renshaw <dwrenshaw@gmail.com>" ]

[[bin]]

name = "server"
path = "src/main.rs"

[dependencies]
gj = "0.2"
gjio = "0.1"
capnp = "0.7"
capnp-rpc = "0.7"
sandstorm = "*"


